let users = [
    {
      id: 0,
      firstName: "Mahir",
      lastName: "KURŞUN",
      job: "Software Engineer",
      isActive: true,
      proflieImagePath: "/images/013.png",
      detail: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, voluptatum vitae officia voluptates ipsa veniam! Numquam ratione voluptas praesentium maxime quam ad assumenda eum non voluptates. Aut nihil cumque reiciendis!`,
    },
    {
      id: 1,
      firstName: "Murat",
      lastName: "OKUR",
      job: "The Analist",
      isActive: true,
      proflieImagePath: "/images/09.png",
      detail: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, voluptatum vitae officia voluptates ipsa veniam! Numquam ratione voluptas praesentium maxime quam ad assumenda eum non voluptates. Aut nihil cumque reiciendis!`,
    },
    {
      id: 2,
      firstName: "Saide Nur",
      lastName: "OKUR",
      job: "Barista",
      isActive: true,
      proflieImagePath: "/images/07.png",
      detail: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, voluptatum vitae officia voluptates ipsa veniam! Numquam ratione voluptas praesentium maxime quam ad assumenda eum non voluptates. Aut nihil cumque reiciendis!`,
    },
    {
      id: 3,
      firstName: "Zeki",
      lastName: "OKUR",
      job: "UX Designer",
      isActive: true,
      proflieImagePath: "/images/08.png",
      detail: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, voluptatum vitae officia voluptates ipsa veniam! Numquam ratione voluptas praesentium maxime quam ad assumenda eum non voluptates. Aut nihil cumque reiciendis!`,
    },
    {
      id: 4,
      firstName: "Hülya",
      lastName: "ÇELEBİ",
      job: ".Net Dveloper",
      isActive: true,
      proflieImagePath: "/images/06.png",
      detail: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, voluptatum vitae officia voluptates ipsa veniam! Numquam ratione voluptas praesentium maxime quam ad assumenda eum non voluptates. Aut nihil cumque reiciendis!`,
    },
    {
      id: 5,
      firstName: "Canbulat",
      lastName: "ONAROK",
      job: "React",
      isActive: true,
      proflieImagePath: "/images/015.png",
      detail: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, voluptatum vitae officia voluptates ipsa veniam! Numquam ratione voluptas praesentium maxime quam ad assumenda eum non voluptates. Aut nihil cumque reiciendis!`,
    },
    {
      id: 6,
      firstName: "Ertan",
      lastName: "ERÖKSÜZ",
      job: "Front-End Developer",
      isActive: true,
      proflieImagePath: "/images/010.png",
      detail: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, voluptatum vitae officia voluptates ipsa veniam! Numquam ratione voluptas praesentium maxime quam ad assumenda eum non voluptates. Aut nihil cumque reiciendis!`,
    },
    {
      id: 7,
      firstName: "Fatih",
      lastName: "OKUR",
      job: "Student",
      isActive: true,
      proflieImagePath: "/images/011.png",
      detail: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, voluptatum vitae officia voluptates ipsa veniam! Numquam ratione voluptas praesentium maxime quam ad assumenda eum non voluptates. Aut nihil cumque reiciendis!`,
    },
    {
      id: 8,
      firstName: "Mehmet",
      lastName: "KAYA",
      job: "Engineer",
      isActive: true,
      proflieImagePath: "/images/03.png",
      detail: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, voluptatum vitae officia voluptates ipsa veniam! Numquam ratione voluptas praesentium maxime quam ad assumenda eum non voluptates. Aut nihil cumque reiciendis!`,
    },
    {
      id: 9,
      firstName: "Derya",
      lastName: "DENİZ",
      job: "Software Engineer",
      isActive: true,
      proflieImagePath: "/images/014.png",
      detail: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, voluptatum vitae officia voluptates ipsa veniam! Numquam ratione voluptas praesentium maxime quam ad assumenda eum non voluptates. Aut nihil cumque reiciendis!`,
    },
    ,
    {
      id: 10,
      firstName: "Ramazan",
      lastName: "YULCA",
      job: "Student",
      isActive: true,
      proflieImagePath: "/images/016.png",
      detail: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, voluptatum vitae officia voluptates ipsa veniam! Numquam ratione voluptas praesentium maxime quam ad assumenda eum non voluptates. Aut nihil cumque reiciendis!`,
    },
    ,
    {
      id: 11,
      firstName: "Deniz",
      lastName: "YAZAR",
      job: "prof",
      isActive: true,
      proflieImagePath: "/images/02.png",
      detail: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, voluptatum vitae officia voluptates ipsa veniam! Numquam ratione voluptas praesentium maxime quam ad assumenda eum non voluptates. Aut nihil cumque reiciendis!`,
    },
  ];